dist: xenial
language: python
python:
  - 3.6
  - 3.7
cache: pypi

install:
  - pip install flake8

script:
  - python -m flake8 my_test_proj/
  - python -m pytest -vvv my_test_proj/

branches:
  only:
  - master


